In [94]:
import numpy as np 

In [95]:
matrix = [[1,1,0,1,0],
          [1,1,1,1,0],
          [0,0,0,0,1],
          [1,0,1,1,1],
          [0,1,0,0,0]]
matrix_arr = np.array([[1,1,0,1,0],
                   [1,1,1,1,0],
                   [0,0,0,0,1],
                   [1,0,1,1,1],
                   [0,1,0,0,0]])

In [96]:
def reflex(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
             if i==j and matrix[i][j] !=1 :
                return False
    return True

In [97]:
def antireflex(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
             if i==j and matrix[i][j] !=0 :
                return False
    return True

In [98]:
def symmerty(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
             if  matrix[i][j] != matrix[j][i]:
                return False
    return True

In [99]:
def asymmerty(matrix):
    if antireflex(matrix) != True:
        return False
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
             if  matrix[i][j]==1 and matrix[j][i]==1 :
                return False
    return True

In [100]:
def antisymmerty(matrix):
    
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
             if  matrix[i][j]==1 and matrix[j][i]==1 and i!=j :
                return False
    return True

In [101]:
def transitive(matrix):
    matrix_2 = np.dot(matrix,matrix)
    if np.min(np.subtract(matrix,matrix_2)) < 0:
        return False
    return True
    
    
            

In [102]:
def worst(matrix):
  l = len(matrix)
  worst_element = []
  for i in range(l):
      if min(matrix[i, :]) == 1:
          worst_element.append(i + 1)
  return worst_element

In [103]:
def best(matrix):
  l = len(matrix)
  best_element = []
  for j in range(l):
      if min(matrix[:, j]) == 1:
          best_element.append(j + 1)
  return best_element

In [104]:
def complement(matrix):
    A = np.ones((5,5))
    r = A - matrix
    return r

In [105]:
def converse(matrix):
    return matrix.transpose()

In [106]:
Max = np.sum(matrix, axis = 0)
print(Max)
def max(matrix):
  
  List = []
  for i in range(len(matrix)):
    if(matrix[i] == 0):
      List.append(i+1)
  return List

[3 3 2 3 2]


In [107]:
Min = np.sum(matrix, axis = 0)
print(Min)
def min(matrix):
  
  List = []
  for i in range(len(matrix)):
    if(matrix[i] == 0):
      List.append(i+1)
  return List

[3 3 2 3 2]


In [108]:

print(reflex(matrix))
print(antireflex(matrix))
print(symmerty(matrix))
print(asymmerty(matrix))
print(antisymmerty(matrix))
print(transitive(matrix_arr))
print(best(matrix_arr))
print(worst(matrix_arr))
print(complement(matrix_arr))
print(converse(matrix_arr))
print(min(Min))
print(max(Max))

False
False
False
False
False
False
[]
[]
[[0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1.]]
[[1 1 0 1 0]
 [1 1 0 0 1]
 [0 1 0 1 0]
 [1 1 0 1 0]
 [0 0 1 1 0]]
[]
[]
