In [1]:
import numpy as np 

In [59]:
def reflex(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
             if i==j and matrix[i][j] !=1 :
                return False
    return True

In [64]:
def antireflex(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
             if i==j and matrix[i][j] !=0 :
                return False
    return True

In [66]:
def symmerty(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
             if  matrix[i][j] != matrix[j][i]:
                return False
    return True

In [71]:
def asymmerty(matrix):
    if antireflex(matrix) != True:
        return False
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
             if  matrix[i][j]==1 and matrix[j][i]==1 :
                return False
    return True

In [75]:
def antisymmerty(matrix):
    
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
             if  matrix[i][j]==1 and matrix[j][i]==1 and i!=j :
                return False
    return True

In [97]:
def transitive(matrix):
    matrix_2 = np.dot(matrix,matrix)
    if np.min(np.subtract(matrix,matrix_2)) < 0:
        return False
    return True
    
    
            

In [101]:
def best(m):
  l = len(m)
  best_element = []
  for i in range(l):
      if min(m[i, :]) == 1:
          best_element.append(i + 1)
  return best_element



In [104]:
def worst(m):
  l = len(m)
  worst_element = []
  for j in range(l):
      if min(m[:, j]) == 1:
          worst_element.append(j + 1)
  return worst_element



In [105]:
matrix = [[1,1,0,1,0],
          [1,1,1,1,0],
          [0,0,0,0,1],
          [1,0,1,1,1],
          [0,1,0,0,0]]
matrix_arr = np.array([[1,1,0,1,0],
                   [1,1,1,1,0],
                   [0,0,0,0,1],
                   [1,0,1,1,1],
                   [0,1,0,0,0]])
matrix_arr_2 = np.dot(matrix_arr,matrix_arr)
log_matrix =[[True,True,False,True,False],
          [True,True,True,True,False],
          [False,False,False,False,True],
          [True,False,True,True,True],
          [False,True,False,False,False]]
print(reflex(matrix))
print(antireflex(matrix))
print(symmerty(matrix))
print(asymmerty(matrix))
print(antisymmerty(matrix))
print(transitive(matrix_arr))
print(best(matrix_arr))
print(worst(matrix_arr))

False
False
False
False
False
False
[]
[]


In [99]:
print(matrix_arr*matrix_arr)
print(np.dot(matrix_arr, matrix_arr))

[[1 1 0 1 0]
 [1 1 1 1 0]
 [0 0 0 0 1]
 [1 0 1 1 1]
 [0 1 0 0 0]]
[[3 2 2 3 1]
 [3 2 2 3 2]
 [0 1 0 0 0]
 [2 2 1 2 2]
 [1 1 1 1 0]]
