In [1]:
import numpy as np 

In [2]:
matrix = [[1,1,0,1,0],
          [1,1,1,1,0],
          [0,0,0,0,1],
          [1,0,1,1,1],
          [0,1,0,0,0]]
matrix_arr = np.array([[1,1,0,1,0],
                   [1,1,1,1,0],
                   [0,0,0,0,1],
                   [1,0,1,1,1],
                   [0,1,0,0,0]])

In [3]:
def reflex(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
             if i==j and matrix[i][j] !=1 :
                return False
    return True

In [4]:
def antireflex(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
             if i==j and matrix[i][j] !=0 :
                return False
    return True

In [5]:
def symmerty(matrix):
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
             if  matrix[i][j] != matrix[j][i]:
                return False
    return True

In [6]:
def asymmerty(matrix):
    if antireflex(matrix) != True:
        return False
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
             if  matrix[i][j]==1 and matrix[j][i]==1 :
                return False
    return True

In [7]:
def antisymmerty(matrix):
    
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
             if  matrix[i][j]==1 and matrix[j][i]==1 and i!=j :
                return False
    return True

In [8]:
def transitive(matrix):
    matrix_2 = np.dot(matrix,matrix)
    if np.min(np.subtract(matrix,matrix_2)) < 0:
        return False
    return True
    
    
            

In [9]:
def worst(matrix):
  l = len(matrix)
  worst_element = []
  if transitive(matrix) == False or (transitive(matrix)== True and reflex(matrix) == True):
     return 'не порядок'
  else:
    for i in range(l):
        if min(matrix[i, :]) == 1:
            worst_element.append(i + 1)
    return worst_element

In [10]:
def best(matrix):
  l = len(matrix)
  best_element = []
  if transitive(matrix) == False or (transitive(matrix)== True and reflex(matrix) == True):
     return 'не порядок'
  else:
    for j in range(l):
        if min(matrix[:, j]) == 1:
            best_element.append(j + 1)
    return best_element

In [11]:
def complement(matrix):
    A = np.ones((5,5))
    r = A - matrix
    return r

In [12]:
def converse(matrix):
    return matrix.transpose()

In [13]:
Max = np.sum(matrix, axis = 0)
print(Max)
def max(matrix):
  
  List = []
  if transitive(matrix) == False or (transitive(matrix)== True and reflex(matrix) == True):
     return 'не порядок'
  else:
    for i in range(len(matrix)):
      if(matrix[i] == 0):
        List.append(i+1)
    return List

[3 3 2 3 2]


In [14]:
Min = np.sum(matrix, axis = 0)
print(Min)
def min(matrix):
  
  List = []
  if transitive(matrix) == False or (transitive(matrix)== True and reflex(matrix) == True):
     return 'не порядок'
  else:
    for i in range(len(matrix)):
      if(matrix[i] == 0):
        List.append(i+1)
    return List

[3 3 2 3 2]


In [15]:

print(reflex(matrix))
print(antireflex(matrix))
print(symmerty(matrix))
print(asymmerty(matrix))
print(antisymmerty(matrix))
print(transitive(matrix_arr))
print(best(matrix_arr))
print(worst(matrix_arr))
print(complement(matrix_arr))
print(converse(matrix_arr))
print(min(Min))
print(max(Max))

False
False
False
False
False
False
не порядок
не порядок
[[0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1.]]
[[1 1 0 1 0]
 [1 1 0 0 1]
 [0 1 0 1 0]
 [1 1 0 1 0]
 [0 0 1 1 0]]
не порядок
не порядок
